ekf_localization:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 1.0
    two_d_mode: false
    publish_tf: true
    publish_acceleration: false
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "map"

    odom0: "/odom"
    odom0_config: [true, true, false, false, false, false, true, true, false, false, false, false, false, false, false]
    odom0_differential: false
    odom0_queue_size: 10
    odom0_nodelay: false
    odom0_relative: true

    imu0: "/imu/data"
    imu0_config: [false, false, false, true, true, true, false, false, false, false, false, false, false, false, false]
    imu0_differential: false
    imu0_queue_size: 10
    imu0_nodelay: false
    imu0_relative: true

